name: duplicate-guard
on:
  pull_request:
    paths: ["content/**/index.mdx"]
  workflow_dispatch:
jobs:
  dupguard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Run similarity guard
        env:
          DUP_GUARD_MIN: "0.45"
          DUP_GUARD_N: "4"
        run: node scripts/similarity_guard.mjs
